# Generated by Django 2.1.1 on 2019-04-11 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LoginApp', '0002_company_gender'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={},
        ),
        migrations.AlterModelOptions(
            name='gender',
            options={},
        ),
    ]
