# Generated by Django 2.1.1 on 2019-04-11 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LoginApp', '0003_auto_20190411_0849'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['company_name']},
        ),
        migrations.AlterModelOptions(
            name='gender',
            options={'ordering': ['gender']},
        ),
    ]
